server.js
=> [NEW] Added a server.js file

practice.c
=> bhagya_practice

stacks.cpp
added stack.cpp
Name: Hemant
#30
=> [new] DSA stack

hacktober pr by vani
=>  V hacktober array !!!!!! 

DakshAggarwal_ArrayReversal.c
Added a file DakshAggarwal_ArrayReversal
#20
=> [NEW] Added a DakshAggarwal_ArrayReversal file

Leetcode_1373.cpp
=> Raghav Added File

bhagya_vowel.c
=> bhagya_vowel

DakshAggarwal_ArrayMerge.c
Added new file DakshAggarwal_ArrayMerge
#17
=> [NEW] Added DakshAggarwal_ArrayMerge file

#@!.html
=> [NEW] Added a file #@!.html

divyanshi_dhawan_assignment_1.c
Hi Divyanshi this side. I just added my file. It was a great experience and i learnt something new.
=> divyanshi_dhawan_assignment_1

.github/workflows/PRERNA_GARG_ASSIGNMENT_4.c
Heyy, I am Prerna Garg. I just added my first file.
=> PRERNA_GARG_ASSIGNMENT_4

.github/workflows/Tulika_jain_assignment_3.c
hi, i am tulika jain. I have added my first file.
=> Tulika_jain_assignment_3

bhagya_char.c
ADDED A NEW FILE WHICH WILL FIND FIRST NON REPEATING CHARACTER 
#14
=> bhagya_char

Stack.cpp
added stack.cpp
Name Hemant 
#20
=> [new] stack reversing array

DakshAggarwal_SecondLargestArray.c
Added a new file DakshAggarwal_SecondLargestArray.c
#18
=> [NEW] Added DakshAggarwal_SecondLargestArray

DakshAggarwal_Strings.c
Added a new file DakshAggarwal_Strings
#15
=> [NEW] Added DakshAggarwal_Strings

bhagya_occu.c
Added a new file which will help find occurrence of characters in a string 
#15
=> bhagya_occurence

prog4.py
=> Anirudh added 2

mazepractice.c
=> aryan added a new file 3

pra.py
=> new file added

aarav.txt
Added a new file aarav.txt
#13
=> [NEW] Added a new file aarav.txt

.github/workflows/jahanvi_wadhwa_assignment_2C.c
=> jahanvi_wadhwa_assignment_2C

Manvi_Palindrome.rtf
Added a new file Manvi_Palindrome
#12
=> [NEW] Added a new file Manvi_Palindrome

missing_number_Hemant.cpp, palindrome_Hemant.cpp
new missing number
name : Hemant
#19
=> missing number

repeating_Hemant.cpp
number of occurrences 
name : Hemant
#15
=> repeating characters

Radix_sort.java
@PHYNiX29 under issue #81 . Please add hacktober accepted label
=> Radix_sort.java

Check_palindrome.cpp
=> Check_palindrome.cpp

Delete_Alternate_Nodes.cpp
Given a Singly Linked List, Delete all alternate nodes of the list ie delete all the nodes present in even positions.
Examples :
Input: LinkedList: 1->2->3->4->5->6
Output: 1->3->5
Explanation: Deleting alternate nodes ie 2, 4, 6 results in the linked list with elements 1->3->5.
=> Delete Alternate Nodes

DFS_recursive.cpp
@PHYNiX29 Kindly add the hacktober label and accept it
=> DFS_recursive.cpp

Lakshay_occurrences.py, lakshay_arraymerge.py, lakshay_palindrome.py, lakshay_radix.txt
added a new file lakshay_radix
#81
=> [new] added a new file lakshay_radix

manvi_occurrences.rtf
Added a new file manvi_occurrences
#15
=> [NEW] Added a new file manvi_occurrences

LoadBalancerDemo.java
Implemented a simple load balancer in java
=> LoadBalancerDemo.java

Solution.java
Fixes : #95 
This solution rotates an array to the right by `k` steps using a three-step reverse process. The algorithm follows these steps:
1. **Calculate Effective Rotation:**
- Since rotating an array by its length results in the same array, we first calculate the effective number of rotations by taking `k % length of array`. This ensures that `k` is within the valid range of the array's length.
2. **Reverse the Entire Array:**
- By reversing the entire array, the last `k` elements are moved to the beginning, and the first elements are pushed to the end.
3. **Reverse the First k Elements:**
- Next, the first `k` elements are reversed again, restoring their original order while keeping them at the start of the array.
4. **Reverse the Remaining Elements:**
- Finally, the remaining …
=> add rotate array in java

Next_Permutation.c
Leetcode Question no : 31 (Medium)
=> Next_Permutation.c

arrayofstrucutes.c, towerofhanoi.c
=> aryan added a file

priya_find_missing_number.cpp
=> added priya_find_missing_number

Hacktoberfest_24_1.cpp, Hacktoberfest_24_2.cpp
=> Parvesh added 3rd file

Tulika_Count occurrences of characters in a string.c
=> Tulika_Count occurrences of characters in a string

PRERNA_GARG_FIND_FIRST_NON_REPEATING_INTEGER.c
=> Prerna added Find first non repeating integer.

mahi_count_vowels.c
=> Mahi added count the number of vowels in a string

Tulika_Count vowels in a string .c
=> Tulika_Count vowels in a string

PRERNA_GARG_COUNT_VOWELS_IN_A_STRING.c
=> Prerna added count vowels in a string.

hybridInheritence.cpp
=> HybridInheritence.cpp

Manvi_MissingNumber.rtf
Added a new file Manvi_MissingNumber
#19
=> [NEW] Added a new file Manvi_MissingNumber

Zaira_count_occurences.c
=> Zaira added count occurences

Zaira_iqbal_first_non_repeating_character.c
=> Zaira added find first non repeating character

Zaira_Iqbal_count_vowels_in_a_string.c, Zaira_Iqbal_merge_two_sorted_arrays.c
=> Zaira added merge two sorted arrays

Zaira_Iqbal_check_if_a_string_is_pallindrome.c
=> Zaira added  check if string is pallindrome

hello.html
=> piyush_occurence

second.cpp, third.cpp
find the missing number in an array
#19
=> Sidd added 2nd file

divyanshi_dhawan_assignment_1.3.c
hi Divyanshiiii this side...having fun doing this workkkk....doing it once more to complete my next pull request
=> hi,Divyanshi this side adding my third file

longest_substring.cpp
added a problem to find longest substring without repeating characters.please assign it to me.
=> Longest substring without repeating characters.

3 Sum.cpp
Explanation
1. Sorting: The array is sorted at the start to make it easier to avoid duplicate triplets.
2. Outer Loop: We iterate through each element in the array. For each element nums[i], we try to find pairs nums[left] and nums[right] such that nums[i] + nums[left] + nums[right] == 0.
3. Two Pointers: For each element nums[i], a two-pointer approach is used to find pairs that sum to -nums[i].
4. Left Pointer: Starts just after i.
5. Right Pointer: Starts at the end of the array.
6. Duplicate Skipping: If we find a triplet, we skip over any duplicate values for both left and right pointers to avoid repeated triplets in the result.
7. Result: The resulting triplets are printed.
=> Create 3 Sum.cpp

Binary Tree Traversal (Inorder, Preorder, Postorder).cpp
1.Inorder Traversal (inorder function)
- Order: Left, Root, Right
- Explanation: The inorder function first recursively calls itself on the left child, then prints the root's data, and finally calls itself on the right child.
- Result: Produces a sorted sequence if the tree is a binary search tree.
2.Preorder Traversal (preorder function)
- Order: Root, Left, Right
- Explanation: This function first prints the root's data, then traverses the left subtree, followed by the right subtree.
- Result: Useful for copying the tree or expressing structure as a list.
3.Postorder Traversal (postorder function)
- Order: Left, Right, Root
- Explanation: This function first recursively visits the left and right children before printing the root's data.
- Result: Useful for deleting or freeing nodes, as …
=> Create Binary Tree Traversal (Inorder, Preorder, Postorder).cpp

BookAllocation.java, BubbleSort.java, BucketSort.java, Dutchflag.java, KruskalAlgorithm.java, PizzaParlourQueue.java, PrimsAlgorithm.java, TowerofHanoi.java
This repository contains a collection of Java implementations for various algorithms and data structures, including:
Bubble Sort: A simple sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order.
Bucket Sort: An efficient sorting algorithm that distributes elements into buckets and then sorts these buckets individually.
Book Allocation Problem: A solution for allocating books to students while minimizing the maximum number of pages assigned to any student.
Dutch National Flag Problem: An algorithm for sorting an array of three distinct values, efficiently organizing them in a single pass.
Kruskal’s Algorithm: An algorithm for finding the minimum spanning tree of a graph, ensuring all vertices are connected with …
=> Program for the Bubble Sort, Bucket Sort, Book Allocation, Dutchflag, Kruskal Algorithm, PizzaParlour Queue program and Prims Alogorithm in Java

RPS-imp-org.html
Rock Paper Scissor Game HTML file
=> Harsh Kumar
